// Copyright 2026 The OpenChoreo Authors
// SPDX-License-Identifier: Apache-2.0

package template

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"sync"
	"sync/atomic"

	"github.com/openchoreo/openchoreo/tools/lint/ruleengine/schema"
	"github.com/openchoreo/openchoreo/tools/lint/templatever"
	"github.com/openchoreo/openchoreo/tools/templates"
)

// schemaFS is the embedded copy of the generated schema sets. The files live in
// the tools/templates/ directory so the schema generator can rewrite them in
// place, which means the //go:embed directive has to sit in that package; it is
// re-exported here under the name the rest of this package uses.
var schemaFS = templates.FS

// templateRoot is the on-disk location of the schema set, relative to the
// working directory, probed for developer overrides before falling back to the
// embedded copy. It must stay in sync with the //go:embed package.
const templateRoot = "tools/templates"

// templateRootLegacy is the pre-move location, still probed so an existing
// checkout keeps working after the schemas move under tools/.
const templateRootLegacy = "templates"

// versionFileName is the manifest written by cmd/schema-gen
// that records every available template version and the latest one. The
// registry reads it so version names are data-driven instead of hard-coded.
const versionFileName = "template-version.json"

// Template versions shipped with occ live in template-v* subfolders
// under tools/templates/. Each folder holds only the JSON schema files
// generated by cmd/schema-gen; the registry code below is shared and
// links with any available version listed in template-version.json.

// LatestVersion is the default template version used when the user has not
// selected another one explicitly. It is populated from template-version.json
// at startup.
var LatestVersion string

// versionsOnce guards the one-time population of LatestVersion and
// availableVersions from template-version.json.
var (
	versionsOnce sync.Once
	versionsErr  error
)

// loadVersions reads template-version.json (preferring the on-disk copy so a
// freshly generated manifest takes effect without rebuilding) and populates
// LatestVersion and availableVersions.
func loadVersions() {
	versionsOnce.Do(func() {
		file := templatever.File{}
		for _, c := range versionFileCandidates() {
			data, err := os.ReadFile(c)
			if err == nil {
				file, err = templatever.Parse(data)
				if err != nil {
					versionsErr = fmt.Errorf("parse %s: %w", c, err)
					return
				}
				populateVersions(file)
				return
			}
		}
		data, err := schemaFS.ReadFile(versionFileName)
		if err != nil {
			versionsErr = fmt.Errorf("read %s: %w", versionFileName, err)
			return
		}
		file, err = templatever.Parse(data)
		if err != nil {
			versionsErr = fmt.Errorf("parse %s: %w", versionFileName, err)
			return
		}
		populateVersions(file)
	})
}

// populateVersions installs the parsed manifest into the package-level state.
func populateVersions(f templatever.File) {
	versions := make([]string, 0, len(f.Versions))
	set := make(map[string]bool, len(f.Versions))
	for _, v := range f.Versions {
		if v == "" || set[v] {
			continue
		}
		set[v] = true
		versions = append(versions, v)
	}
	availableVersions = versions
	LatestVersion = f.Latest
	if LatestVersion == "" || !contains(availableVersions, LatestVersion) {
		LatestVersion = latestOf(versions)
	}
}

// latestOf returns the greatest version of the given list.
func latestOf(versions []string) string {
	if len(versions) == 0 {
		return ""
	}
	best := versions[0]
	for _, v := range versions[1:] {
		if templatever.Compare(v, best) > 0 {
			best = v
		}
	}
	return best
}

// contains reports whether v is present in versions.
func contains(versions []string, v string) bool {
	for _, x := range versions {
		if x == v {
			return true
		}
	}
	return false
}

// versionFileCandidates lists the on-disk locations probed for the manifest
// before falling back to the embedded copy.
func versionFileCandidates() []string {
	exeDir := ""
	if exe, err := os.Executable(); err == nil {
		exeDir = filepath.Dir(exe)
	}
	candidates := []string{versionFileName}
	if exeDir != "" {
		candidates = append(candidates, filepath.Join(exeDir, versionFileName))
	}
	for _, base := range []string{
		filepath.Join(templateRoot, versionFileName),
		filepath.Join(templateRootLegacy, versionFileName),
	} {
		candidates = append(candidates, base)
	}
	return candidates
}

// AvailableVersions returns the names of every template version shipped with
// occ, sorted ascending.
func AvailableVersions() []string {
	loadVersions()
	out := make([]string, len(availableVersions))
	copy(out, availableVersions)
	return out
}

// kindSpec describes one kind validated by the rule engine: the embedded JSON
// schema file, the prefix used in diagnostic codes, and the human-readable
// rule name. The kind set is identical across template versions; only the
// schema contents differ, so this list is shared.
type kindSpec struct {
	kind     string
	prefix   string
	ruleName string
	file     string
}

// kinds is the registry of every kind the rule engine validates. It is the
// single source of truth consumed by RulesForKind, AllKinds, and SchemaFor.
// The file list mirrors the output of cmd/schema-gen.
var kinds = []kindSpec{
	{kind: "Project", prefix: "project", ruleName: "project-rules", file: "project_minimal_defi.json"},
	{kind: "Component", prefix: "component", ruleName: "component", file: "component_minimal_defi.json"},
	{kind: "ComponentType", prefix: "component-type", ruleName: "componenttype-rules", file: "component_type_minimal_defi.json"},
	{kind: "ClusterComponentType", prefix: "cluster-component-type", ruleName: "clustercomponenttype-rules", file: "cluster_component_type_minimal_defi.json"},
	{kind: "Environment", prefix: "environment", ruleName: "environment-rules", file: "environment_minimal_def.json"},
	{kind: "DeploymentPipeline", prefix: "deploymentpipeline", ruleName: "deploymentpipeline-rules", file: "deploymentpipelines_minimal_defi.json"},
	{kind: "ProjectReleaseBinding", prefix: "project-release-binding", ruleName: "projectreleasebinding-rules", file: "project_release_binding_minimal_defi.json"},
	{kind: "ReleaseBinding", prefix: "release-binding", ruleName: "releasebinding-rules", file: "release_binding_minimal_defi.json"},
	{kind: "Workflow", prefix: "workflow", ruleName: "workflow-rules", file: "workflow_minimal_defi.json"},
	{kind: "ClusterWorkflow", prefix: "cluster-workflow", ruleName: "clusterworkflow-rules", file: "clusterworkflows_minimal_defi.json"},
	{kind: "WorkflowRun", prefix: "workflow-run", ruleName: "workflowrun-rules", file: "workflow_run_minimal_defi.json"},
	{kind: "Workload", prefix: "workload", ruleName: "workload-rules", file: "workload_minimal_defi.json"},
	{kind: "ClusterProjectType", prefix: "cluster-project-type", ruleName: "clusterprojecttype-rules", file: "cluster_project_type_minimal_defi.json"},
	{kind: "ClusterResourceType", prefix: "cluster-resource-type", ruleName: "clusterresourcetype-rules", file: "cluster_resource_type_minimal_defi.json"},
	{kind: "ResourceType", prefix: "resource-type", ruleName: "resourcetype-rules", file: "resource_type_minimal_defi.json"},
	{kind: "ClusterDataPlane", prefix: "cluster-data-plane", ruleName: "clusterdataplane-rules", file: "cluster_data_plane_minimal_defi.json"},
	{kind: "ClusterObservabilityPlane", prefix: "cluster-observability-planes", ruleName: "cluster-observability-planes-rules", file: "clusterobservabilityplanes_minimal_defi.json"},
	{kind: "Trait", prefix: "trait", ruleName: "trait-rules", file: "trait_minimal_defi.json"},
	{kind: "ClusterTrait", prefix: "cluster-trait", ruleName: "cluster-trait", file: "clustertrait_minimal_defi.json"},
	// Namespaced config kinds.
	{kind: "AuthzRole", prefix: "authz-role", ruleName: "authz-role-rules", file: "authz_role_minimal_defi.json"},
	{kind: "AuthzRoleBinding", prefix: "authz-role-binding", ruleName: "authz-role-binding-rules", file: "authz_role_binding_minimal_defi.json"},
	{kind: "DataPlane", prefix: "data-plane", ruleName: "data-plane-rules", file: "data_plane_minimal_defi.json"},
	{kind: "ObservabilityAlertRule", prefix: "observability-alert-rule", ruleName: "observability-alert-rule-rules", file: "observability_alert_rule_minimal_defi.json"},
	{kind: "ObservabilityAlertsNotificationChannel", prefix: "observability-alerts-notification-channel", ruleName: "observability-alerts-notification-channel-rules", file: "observability_alerts_notification_channel_minimal_defi.json"},
	{kind: "ObservabilityPlane", prefix: "observability-plane", ruleName: "observability-plane-rules", file: "observability_plane_minimal_defi.json"},
	{kind: "ProjectType", prefix: "project-type", ruleName: "project-type-rules", file: "project_type_minimal_defi.json"},
	{kind: "Resource", prefix: "resource", ruleName: "resource-rules", file: "resource_minimal_defi.json"},
	{kind: "ResourceReleaseBinding", prefix: "resource-release-binding", ruleName: "resource-release-binding-rules", file: "resource_release_binding_minimal_defi.json"},
	{kind: "SecretReference", prefix: "secret-reference", ruleName: "secret-reference-rules", file: "secret_reference_minimal_defi.json"},
	{kind: "WorkflowPlane", prefix: "workflow-plane", ruleName: "workflow-plane-rules", file: "workflow_plane_minimal_defi.json"},
	// Namespaced controller-managed release artifacts.
	{kind: "ComponentRelease", prefix: "component-release", ruleName: "component-release-rules", file: "component_release_minimal_defi.json"},
	{kind: "ProjectRelease", prefix: "project-release", ruleName: "project-release-rules", file: "project_release_minimal_defi.json"},
	{kind: "RenderedRelease", prefix: "rendered-release", ruleName: "rendered-release-rules", file: "rendered_release_minimal_defi.json"},
	{kind: "ResourceRelease", prefix: "resource-release", ruleName: "resource-release-rules", file: "resource_release_minimal_defi.json"},
	// Cluster-scoped kinds.
	{kind: "ClusterAuthzRole", prefix: "cluster-authz-role", ruleName: "cluster-authz-role-rules", file: "cluster_authz_role_minimal_defi.json"},
	{kind: "ClusterAuthzRoleBinding", prefix: "cluster-authz-role-binding", ruleName: "cluster-authz-role-binding-rules", file: "cluster_authz_role_binding_minimal_defi.json"},
	{kind: "ClusterWorkflowPlane", prefix: "cluster-workflow-plane", ruleName: "cluster-workflow-plane-rules", file: "cluster_workflow_plane_minimal_defi.json"},
}

var (
	kindIndex         = make(map[string]kindSpec, len(kinds))
	allKindNames      = make([]string, 0, len(kinds))
	loadOnce          sync.Once
	loadErr           error
	currentVersionVal atomic.Value
	availableVersions []string
)

// init stores the default template version. It must run after loadVersions so
// SchemaFor/RulesForKind work even before SetVersion is called.
func init() {
	loadVersions()
	currentVersionVal.Store(LatestVersion)
}

// currentVersion returns the active template version as a string.
func currentVersion() string {
	return currentVersionVal.Load().(string)
}

// load builds the versioned schema maps and the kind-name index. It is called
// lazily on first use and reports failures as errors instead of panicking.
func load() error {
	loadOnce.Do(func() {
		for _, ks := range kinds {
			kindIndex[ks.kind] = ks
			allKindNames = append(allKindNames, ks.kind)
		}
		schemasByVersion = make(map[string]map[string]*schema.FieldSchema, len(availableVersions))
		for _, ver := range availableVersions {
			byKind := make(map[string]*schema.FieldSchema, len(kinds))
			for _, ks := range kinds {
				data, err := readSchemaFile(ver, ks.file)
				if err != nil {
					loadErr = fmt.Errorf("read schema %s (template %s): %w", ks.file, ver, err)
					return
				}
				parsed, err := schema.Parse(data)
				if err != nil {
					loadErr = fmt.Errorf("parse schema %s (template %s): %w", ks.file, ver, err)
					return
				}
				byKind[ks.kind] = parsed
			}
			schemasByVersion[ver] = byKind
		}
	})
	return loadErr
}

// schemasByVersion holds the parsed FieldSchema for every kind per template
// version. It is populated by load and read-only afterwards.
var schemasByVersion map[string]map[string]*schema.FieldSchema

// SetVersion selects the template version used by SchemaFor, RulesForKind,
// and AllKinds. It accepts a concrete version such as "v1.2.0" or the alias
// "latest" (which maps to LatestVersion). An unknown version is rejected with
// an error listing the available versions.
func SetVersion(version string) error {
	if version == "" || version == "latest" {
		version = LatestVersion
	}
	for _, v := range availableVersions {
		if version == v {
			// Eagerly load so a bad/broken version surfaces before it is used.
			if err := load(); err != nil {
				return fmt.Errorf("load template %s: %w", version, err)
			}
			currentVersionVal.Store(version)
			return nil
		}
	}
	return fmt.Errorf("unknown template version %q (available: %s)", version, strings.Join(availableVersions, ", "))
}

// CurrentVersion returns the active template version. When no explicit
// selection has been made it returns LatestVersion.
func CurrentVersion() string {
	return currentVersion()
}

// LoadError returns the error that occurred while loading the template
// version manifest or the schema registry, or nil when both loaded
// successfully or have not been loaded yet.
func LoadError() error {
	loadVersions()
	if versionsErr != nil {
		return versionsErr
	}
	return load()
}

// SchemaFor returns the parsed FieldSchema for the given kind in the active
// template version, or nil if unknown.
func SchemaFor(kind string) *schema.FieldSchema {
	if load() != nil {
		return nil
	}
	return schemasByVersion[currentVersion()][kind]
}

// versionDir returns the subdirectory holding the schema files for a version.
func versionDir(version string) string {
	return "template-" + version
}

// readSchemaFile loads a schema JSON file for the given template version,
// preferring the on-disk copy so that edits take effect without rebuilding.
func readSchemaFile(version, file string) ([]byte, error) {
	dir := "template-" + version
	exeDir := ""
	if exe, err := os.Executable(); err == nil {
		exeDir = filepath.Dir(exe)
	}
	candidates := []string{file}
	if exeDir != "" {
		candidates = append(candidates, filepath.Join(exeDir, file))
	}
	for _, base := range []string{
		filepath.Join(templateRoot, dir),
		filepath.Join(templateRootLegacy, dir),
	} {
		candidates = append(candidates, filepath.Join(base, file))
	}
	for _, c := range candidates {
		data, err := os.ReadFile(c)
		if err == nil {
			return data, nil
		}
	}
	return schemaFS.ReadFile(filepath.Join(dir, file))
}
